### ISSUE TITLE
no matches for kind "PrometheusServiceLevel" in version "sloth.slok.dev/v1"

### ISSUE THREAD

**Issue by LH8PPL** [slok/sloth#202]
Hi,
i tried to deploy Sloth on my kube cluster with the deployment below but then got the following error:
```
INFO[0000] SLI plugins loaded                            plugins=0 svc=storage.FileSLIPlugin version=v0.8.0 window=30d
INFO[0000] Loading Kubernetes configuration...           version=v0.8.0
error: "kubernetes-controller" command failed: check for PrometheusServiceLevel CRD failed: could not list: the server could not find the requested resource (get prometheusservicelevels.sloth.slok.dev)
```
then I tried to deploy a PrometheusServiceLevel, see below, and then got this:
`error: unable to recognize "sloth-k8s-getting-started.yml": no matches for kind "PrometheusServiceLevel" in version "sloth.slok.dev/v1"`

What am I doing wrong?

deployment:
https://github.com/slok/sloth/blob/main/deploy/kubernetes/raw/sloth.yaml

PrometheusServiceLevel deployment:
https://github.com/slok/sloth/blob/main/examples/k8s-multifile.yml

**Comment by slok** [comment]
Hi @LH8PPL 

Sloth uses `sloth.slok.dev/v1/PrometheusServiceLevel` CRs, so you need to set the CRD on your Kubernetes cluster. The first error is Sloth checking if the cluster has the CRD installed, and the second one is the API server telling you that doesn't know that resources (because of the missing CRD).

Form the [Docs](https://sloth.dev/usage/kubernetes/):

>Sloth CRD is required
>Example:
> `$ kubectl apply -f ./pkg/kubernetes/gen/crd/sloth.slok.dev_prometheusservicelevels.yaml`

Take into account that in Kubernetes mode you will need also Prometheus Operator CRDs (there is a warning on the same doc page).

**Comment by LH8PPL** [comment]
Thank you for the quick replay.
I don't know how I missed it in the docs.
It worked, thank you.
