### ISSUE TITLE
Make OptimizedSLIRecordGenerator optional

### ISSUE THREAD

**Issue by tokheim** [slok/sloth#241]
In https://github.com/slok/sloth/blob/main/internal/prometheus/recording_rules.go#L53 the SLI for the SLO-period is always calculated using a optimized calculation method. When there isn't uniform load on a service the result of the optimized method can differ quite a lot from a calculation using errors divided by total. An example can be seen below where traffic (green) is very uneven, and the optimized calculation (yellow) underestimates the error rate many times over compared to the regular (blue) calculation.

![image](https://user-images.githubusercontent.com/867076/151662681-539938f9-5a21-47df-82d1-fb5e845391ba.png)

This comes from the optimized calcuation assuming that each 5m slice are equally important for the overall SLO. You can even see that while the blue line stays static in periods with no traffic, the yellow error rate slowly decreases.

Granted there isn't any broad consensus on how SLOs should be calculated, it is a topic with passionate debate. One example discussing the fairness of using ratio based SLOs can be found in https://grafana.com/blog/2019/11/27/kubecon-recap-how-to-include-latency-in-slo-based-alerting/

> “ISPs love to tell you they have 99.9% uptime. What does that mean? This implies it’s time-based, but all night I’m asleep, I am not using my internet connection. And even if there’s a downtime, I won’t notice and my ISP will tell me they were up all the time. Not using the service is like free uptime for the ISP. Then I have a 10-minute, super important video conference, and my internet connection goes down. That’s for me like a full outage. And they say, yeah, 10 minutes per month, that’s three nines, it’s fine.”
> 
> A better alternative: a request-based SLA that says, “During each month we’ll serve 99% of requests successfully.”

Would there be any interest in making the OptimizedSLIRecordGenerator optional? With some input on how a user could control this, I'd be happy to try to create a pull request.

**Comment by tokheim** [comment]
Oh, and using the non-optimized calculation would also partially help for people experiencing NaNs like #231  in the period budget. If there is a NaN in any 5 minute slice, then the whole optimized sli recorder expression will evaluate to NaN. I guess there are other ways this could be improved though...

**Comment by slok** [comment]
Hi again @tokheim 

That optimization was made because normally most people only want the 30d as an informative metric (not used for alerting or similar things) and the approximation works in most cases (well, Prometheus itself is also an approximation of reality), not having it would kill a lot of Prometheus installations (due to queries) or end having no metric because of timeouts on the rules.

You are the first person (that I'm aware of) that this doesn't work for him/her.

Let me think about adding this option, in case it's added, it would be done at the application level (with a flag) and not at the SLO level, I would prefer to maintaint the specs as simple as possible.

Regarding the NaNs, it's a different problem that should be solved with the right queries (using a combination of `>0`, `vector(0)`...).

**Comment by tokheim** [comment]
Hi @slok,

Sorry for causing trouble again. Unfortunately we have some services that e.g. are only in use while formula1 events happen, which is some hours every Sunday and such, that would suffer a bit from this. I actually see it a bit differently, that it could be an ok approximation for alerting, while the slo-period is the actual contract the team commits to. Alerting is just there to help the team reach the contract.

Completely agree that you are better off doing `>0 or vector(1)` things to avoid NaNs in the first place. The only real shortcoming I see the library could solve is that if you mess up the query, you have to wait 30d until the NaNs are scrubbed from prometheus. So maybe the optimized rule should more do
```
sum_over_time(x > 0) /
count_over_time(x > 0)
```
to simply disregard NaNs.

**Comment by xairos** [comment]
> You are the first person (that I'm aware of) that this doesn't work for him/her

I wanted to add a +1 to say that we'd benefit as well from this! 

> I actually see it a bit differently, that it could be an ok approximation for alerting, while the slo-period is the actual contract the team commits to. Alerting is just there to help the team reach the contract.

I have this perspective as well, and before looking at the PromQL that Sloth generates, I actually thought that Sloth would use this method for calculating `slo:period_error_budget_remaining:ratio`. I had been (erroneously) expecting that the SLOs would be calculated using `good events / total events` (rather than `good time / total time` using the optimized calculation).

We have many services with varying traffic patterns, ex. internal apps used by customer service that have almost no traffic outside of customer support hours. If those SLOs could be calculated using `good events / total events`, they would become more useful for reporting 👍🏻

**Comment by slok** [comment]
Awesome @tokheim @xairos, thanks for your inputs and raising your hand. Is very valuable to see that is not an isolated case.

I'll think about this, but most likely that this will be on the next release :)

Again many thanks!

**Comment by jenniejia** [comment]
Hello Guys,

We just integrated Sloth SLO Spec to our systems, We used two SLO dashboard from here https://sloth.dev/introduction/dashboards/

Run some traffic and Observed the SLO dashboard, see this "NaN" issue, this is why I am here.. it is Year 2024.. By reading this thread. Do we have better solution instead of doing >0 or vector(1) things to avoid NaNs in the first place.  But how to fix this PromQL query?

![NaN_issue](https://github.com/slok/sloth/assets/52936281/0411b828-a54b-46ca-a220-3cc57ea6afee)



Thanks!
