### ISSUE TITLE
Query SLO monthly

### ISSUE THREAD

**Issue by kyledakid** [slok/sloth#242]
Hi Xabier,

This is not an issue.

I saw that on Sloth Dashboard, we have the Dashboard to show Remaining error budget for the current month.
![image](https://user-images.githubusercontent.com/12691265/151701287-0dd02261-88e2-48b3-bc50-b1c2b71929f6.png)

Is there a way to query this metric i**n a monthly manner** ? Something like: Assumpt that current month is February. I set Grafana From and To back to 30 Nov and 30 Jan. So I'd got a dashboard of Remaining Error budget reseted at 100% at the beginning of each Month 

My actual goal is: I need to know my service SLO compliance through out the months, to see which months it used all the error budget.

**Comment by slok** [comment]
Hey @kyledakid!

Its tricky because those metrics are very hacky to be able to show them on Grafana (if you check the query is pretty complex and uses Grafana internal variables also).

My recommendation here is to query your remaining error budget period window in specific timestamps (`slo:period_error_budget_remaining:ratio`). For example with a script or something that creates you a report or similar.

If you need something visual in Grafana, you could create a Graph with a step of the window you want to measure. For example, this would be for a period of 15 days, the error remaining budget every 2 days.

![Screenshot_20220201_083225](https://user-images.githubusercontent.com/128204/151929117-0edb014c-f68d-42c7-b108-ce50ed149c77.png)

In your example your min step could be `30d` and the way you visualize it depends on what you want (bars, points, aggregation filtering...).

Hope this helps!

**Comment by kyledakid** [comment]
Great idea. I see, Xabier 👍 
Thanks for the tip.
I'm closing this.
