### ISSUE TITLE
How does the error budget calculation work?

### ISSUE THREAD

**Issue by jimethn** [slok/sloth#332]
slo:sli_error:ratio_rate30d [is calculated as](https://github.com/slok/sloth/blob/c4bc48bd839e4dc96c199784340fea8c2fdd6e77/examples/_gen/getting-started.yml#L107-L111)
```
sum_over_time(slo:sli_error:ratio_rate5m[30d])
/
count_over_time(slo:sli_error:ratio_rate5m[30d])
```

slo:sli_error:ratio_rate30d is then [used to calculate](https://github.com/slok/sloth/blob/c4bc48bd839e4dc96c199784340fea8c2fdd6e77/examples/_gen/getting-started.yml#L159-L174) slo:period_burn_rate:ratio and slo:period_error_budget_remaining:ratio.

If I'm reading that right, doesn't that mean we are taking all the 5 minute windows and averaging them together with equal weight? If it were truly events-based, then each window should be weighted by the number of requests within that window, but this seems like we are averaging an average. Or am I misunderstanding how these aggregations work? Sorry if this is a stupid question!

**Comment by slok** [comment]
Hi @jimethn 

Those are optimized rules for 30d windows that lots of prometheus installations end dying there (rule timeout, expensive queries...), that's why I did that, you get the less precision metric instead of not getting anything or killing Prometheus.

If you want the real value and make the expensive queries you can use `--disable-optimized-rules`

**Comment by jimethn** [comment]
Makes sense, thank you!
