### ISSUE TITLE
Generate yaml without Alerts

### ISSUE THREAD

**Issue by KaiReichart** [slok/sloth#94]
Hi, is it possible to create SLOs without alerts?   
If not, would this be something you would consider?

**Comment by slok** [comment]
Hey @KaiReichart!

You can! On each of the different alerts (`page` and `warning`) you can use `disable: true`.

- [`prometheus/v1`](https://github.com/slok/sloth/tree/main/pkg/prometheus/api/v1#type-alert)
- [K8s `sloth.slok.dev/v1/PrometheusServiceLevel` CRD]( https://github.com/slok/sloth/tree/main/pkg/kubernetes/api/sloth/v1#type-alert)

An example using `prometheus/v1` spec: https://github.com/slok/sloth/blob/main/examples/no-alerts.yml

**Comment by KaiReichart** [comment]
Ah, cool thanks! Any specific reason why just omitting `slo.[].alerting` isn't supported? I think this might be more intuitive than the current implementation

**Comment by slok** [comment]
Yes, I wanted to be explicit regarding this, mainly because YAML introduces a lots of non desired outcomes, for example bad indentation on an Alerting block being ignored, however having the alerting block configured.

So, by default the alerts are activated and need to be configured (validation) using a required name. And if you want to disable you must be explicit with this.

I preferred being explicit and adding a bit of verbosity in favor of having more reliable configurations and avoiding bugs on YAMLS.

**Comment by KaiReichart** [comment]
makes total sense, thanks for the explanation!
